name: Deploy on Push to Main
on:
  push:
    branches:
      - main
jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Install expect
        run: |
          sudo apt-get update
          sudo apt-get install expect
      
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Determine changes
        id: determine_changes
        run: |
          changed_files="$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          echo "::set-output name=changed_files::$changed_files"
          
      - name: Build Blog
        if: ${{ contains(steps.determine_changes.outputs.changed_files, 'blog/') }}
        working-directory: apps/blog
        run: |
          pnpm install
          npx turbo run build
          
      - name: Deploy Blog if changed
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          expect << EOF
          spawn vercel --prod --token $VERCEL_TOKEN
          expect "Set up and deploy"
          send "Y\r"
          expect "abcd"
          send "\r"
          expect "abcd"
          send "Y\r"
          expect eof
          EOF
        
  deploy-lab:
    runs-on: ubuntu-latest
    steps:
      - name: Install expect
        run: |
          sudo apt-get update
          sudo apt-get install expect

      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Determine changes
        id: determine_changes
        run: |
          changed_files="$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          echo "::set-output name=changed_files::$changed_files"
          
      - name: Build lab
        if: ${{ contains(steps.determine_changes.outputs.changed_files, 'lab/') }}
        working-directory: apps/lab
        run: |
          pnpm install
          npx turbo run build
      
      - name: Deploy Lab if changed
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_PROJECTID_LAB }}
        run: |
          expect << EOF
          spawn vercel --prod --token $VERCEL_TOKEN
          expect "Set up and deploy"
          send "Y\r"
          expect "abcd"
          send "\r"
          expect "abcd"
          send "n\r"
          expect "abcd"
          send "Y\r"
          expect "abcd"
          send "blog-lab\r"
          expect eof
          EOF
